version: "3.3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/.docker/quieroretruco/mongo:/data/db
  api:
    build: ./app/
    volumes:
      - ./app:/app
    ports:
      - 8001:8001
    environment:
     - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb
  nextjs:
    ports:
      - 3000:3000
    build: ./client/
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - api
